FlatterScatter
alpaka-group/mallocMC pull request #271
Opened 2024-11-12 15:09 UTC by chillenzer

This PR adds amongst a number of modernisations the new FlatterScatter creation policy.

2024-11-25 08:50 UTC, psychocoderHPC requested changes
offline discussed catch2 should be fetched on the need to not increase the repository size to much.

The rest looks good! ONly one small question for the heap init part is open.

2024-11-25 08:50 UTC, psychocoderHPC commented on examples/mallocMC_example01.cpp
>  ALPAKA_STATIC_ACC_MEM_GLOBAL int** arA;
IMO this must be equal to https://github.com/alpaka-group/alpaka/blob/7e1b6ce24c5fadc9c58dd0d1dc59c022e96a087b/test/unit/mem/view/src/ViewStaticAccMem.cpp#L19

`alpaka::DevGlobal` is missing and the usage requires a `.get()` but it looks it runs and the `DevGlobal` is only required for SYCL. SO I am fine to keep it as it is.

2024-11-25 08:50 UTC, psychocoderHPC commented on src/include/mallocMC/creationPolicies/FlatterScatter.hpp
> +            alpaka::memset(queue, poolView, 0U);
note: You mentioned last time offline that we use a kernel to initialize the heap but here the memset is still present. It is fine for this PR I would like to avoid that we use memset and a on device initialization.

2024-11-25 08:50 UTC, psychocoderHPC commented on src/include/mallocMC/creationPolicies/FlatterScatter.hpp
> +            alpaka::exec<TAcc>(queue, workDivSingleThread, FlatterScatterAlloc::InitKernel{}, heap, pool, memsize);
This sounds like the kernel which is performing the on device init equal to the memset above.

2024-11-25 08:50 UTC, psychocoderHPC commented on src/include/mallocMC/creationPolicies/FlatterScatter/AccessBlock.hpp
> +            // TODO(lenz): This is not thread-safe!
we should not forget this todo and handle it in a future PR

2024-11-25 08:50 UTC, psychocoderHPC commented on src/include/mallocMC/creationPolicies/FlatterScatter/AccessBlock.hpp
> +            uint32_t& chunkSizeCache) -> bool
only a note: this should be refactored in the future and return the value together with the current return value as tuple.

2024-11-25 11:58 UTC, chillenzer commented on src/include/mallocMC/creationPolicies/FlatterScatter.hpp
> +            alpaka::memset(queue, poolView, 0U);
Oh, good catch! There is an `init` method for the heap but apparently it is unused. It's on my TODO list.

2024-11-25 12:43 UTC, chillenzer commented on src/include/mallocMC/creationPolicies/FlatterScatter/AccessBlock.hpp
> +            // TODO(lenz): This is not thread-safe!
This is kind of a minor issue: The informational methods `getAvailableSlots` and its helpers provide information that cannot possibly be used in a thread-safe manner. So, calling them while other threads are write-accessing the same allocator is not a reasonable thing to do anyways. Mostly left it in for informational purposes but maybe I should drop the `TODO(lenz)` part. It is documented in the `Usage.md` document by the way.

2024-11-25 12:47 UTC, chillenzer commented on examples/mallocMC_example01.cpp
>  ALPAKA_STATIC_ACC_MEM_GLOBAL int** arA;
Opened: https://github.com/alpaka-group/mallocMC/issues/272 to track this.

2024-11-25 12:47 UTC, chillenzer commented on src/include/mallocMC/creationPolicies/FlatterScatter.hpp
> +            alpaka::memset(queue, poolView, 0U);
Opened https://github.com/alpaka-group/mallocMC/issues/273 to track this.

2024-11-25 12:55 UTC, chillenzer commented on src/include/mallocMC/creationPolicies/FlatterScatter.hpp
> +            alpaka::exec<TAcc>(queue, workDivSingleThread, FlatterScatterAlloc::InitKernel{}, heap, pool, memsize);
Oh, damn! It's much worse! The above memset is completely redundant. -.-

2024-11-25 12:56 UTC, chillenzer commented on src/include/mallocMC/creationPolicies/FlatterScatter/AccessBlock.hpp
> +            uint32_t& chunkSizeCache) -> bool
Opened https://github.com/alpaka-group/mallocMC/issues/274 to track this.

2024-11-25 13:02 UTC, chillenzer commented
Okay. I've surgically removed the Catch2 commit and replaced it with a git submodule. I've removed the redundant `memset` in the init method and will certainly do the initialisation benchmark again! Other than that I've opened issues to track your good suggestions.

2024-11-26 12:34 UTC, psychocoderHPC approved these changes

2024-11-26 12:35 UTC, merged